packages:
  - 'packages/*'
  - 'apps/*'

onlyBuiltDependencies:
  - esbuild
  - lefthook

allowBuilds:
  esbuild: true
  lefthook: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.4'
  - '@tanstack/react-query@5.101.4'
  - react@19.2.8
  - react-dom@19.2.8
