/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Reset_passwordRouteImport } from './routes/reset_password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCardsRouteImport } from './routes/admin/cards'
import { Route as AdminMonitorRouteImport } from './routes/admin/monitor'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminBuildingsBuildingIdRouteImport } from './routes/admin/buildings.$buildingId'
import { Route as AdminBuildingsBuildingIdIndexRouteImport } from './routes/admin/buildings.$buildingId/index'
import { Route as AdminBuildingsBuildingIdApartmentsRouteImport } from './routes/admin/buildings.$buildingId/apartments'
import { Route as AdminBuildingsBuildingIdEventsRouteImport } from './routes/admin/buildings.$buildingId/events'
import { Route as AdminBuildingsBuildingIdLiveRouteImport } from './routes/admin/buildings.$buildingId/live'
import { Route as AdminBuildingsBuildingIdReadersRouteImport } from './routes/admin/buildings.$buildingId/readers'
import { Route as AdminBuildingsBuildingIdSettingsRouteImport } from './routes/admin/buildings.$buildingId/settings'
import { Route as AdminBuildingsBuildingIdUsersRouteImport } from './routes/admin/buildings.$buildingId/users'
import { Route as AdminBuildingsBuildingIdApartmentsIndexRouteImport } from './routes/admin/buildings.$buildingId/apartments.index'
import { Route as AdminBuildingsBuildingIdApartmentsApartmentIdUsersRouteImport } from './routes/admin/buildings.$buildingId/apartments.$apartmentId.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Reset_passwordRoute = Reset_passwordRouteImport.update({
  id: '/reset_password',
  path: '/reset_password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitorRoute = AdminMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildingsBuildingIdRoute =
  AdminBuildingsBuildingIdRouteImport.update({
    id: '/buildings/$buildingId',
    path: '/buildings/$buildingId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBuildingsBuildingIdIndexRoute =
  AdminBuildingsBuildingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdApartmentsRoute =
  AdminBuildingsBuildingIdApartmentsRouteImport.update({
    id: '/apartments',
    path: '/apartments',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdEventsRoute =
  AdminBuildingsBuildingIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdLiveRoute =
  AdminBuildingsBuildingIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdReadersRoute =
  AdminBuildingsBuildingIdReadersRouteImport.update({
    id: '/readers',
    path: '/readers',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdSettingsRoute =
  AdminBuildingsBuildingIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdUsersRoute =
  AdminBuildingsBuildingIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdApartmentsIndexRoute =
  AdminBuildingsBuildingIdApartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminBuildingsBuildingIdApartmentsRoute,
  } as any)
const AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute =
  AdminBuildingsBuildingIdApartmentsApartmentIdUsersRouteImport.update({
    id: '/$apartmentId/users',
    path: '/$apartmentId/users',
    getParentRoute: () => AdminBuildingsBuildingIdApartmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/reset_password': typeof Reset_passwordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/buildings/$buildingId': typeof AdminBuildingsBuildingIdRouteWithChildren
  '/admin/buildings/$buildingId/apartments': typeof AdminBuildingsBuildingIdApartmentsRouteWithChildren
  '/admin/buildings/$buildingId/events': typeof AdminBuildingsBuildingIdEventsRoute
  '/admin/buildings/$buildingId/live': typeof AdminBuildingsBuildingIdLiveRoute
  '/admin/buildings/$buildingId/readers': typeof AdminBuildingsBuildingIdReadersRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
  '/admin/buildings/$buildingId/users': typeof AdminBuildingsBuildingIdUsersRoute
  '/admin/buildings/$buildingId/': typeof AdminBuildingsBuildingIdIndexRoute
  '/admin/buildings/$buildingId/apartments/': typeof AdminBuildingsBuildingIdApartmentsIndexRoute
  '/admin/buildings/$buildingId/apartments/$apartmentId/users': typeof AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/reset_password': typeof Reset_passwordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/buildings/$buildingId/events': typeof AdminBuildingsBuildingIdEventsRoute
  '/admin/buildings/$buildingId/live': typeof AdminBuildingsBuildingIdLiveRoute
  '/admin/buildings/$buildingId/readers': typeof AdminBuildingsBuildingIdReadersRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
  '/admin/buildings/$buildingId/users': typeof AdminBuildingsBuildingIdUsersRoute
  '/admin/buildings/$buildingId': typeof AdminBuildingsBuildingIdIndexRoute
  '/admin/buildings/$buildingId/apartments': typeof AdminBuildingsBuildingIdApartmentsIndexRoute
  '/admin/buildings/$buildingId/apartments/$apartmentId/users': typeof AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/reset_password': typeof Reset_passwordRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/buildings/$buildingId': typeof AdminBuildingsBuildingIdRouteWithChildren
  '/admin/buildings/$buildingId/apartments': typeof AdminBuildingsBuildingIdApartmentsRouteWithChildren
  '/admin/buildings/$buildingId/events': typeof AdminBuildingsBuildingIdEventsRoute
  '/admin/buildings/$buildingId/live': typeof AdminBuildingsBuildingIdLiveRoute
  '/admin/buildings/$buildingId/readers': typeof AdminBuildingsBuildingIdReadersRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
  '/admin/buildings/$buildingId/users': typeof AdminBuildingsBuildingIdUsersRoute
  '/admin/buildings/$buildingId/': typeof AdminBuildingsBuildingIdIndexRoute
  '/admin/buildings/$buildingId/apartments/': typeof AdminBuildingsBuildingIdApartmentsIndexRoute
  '/admin/buildings/$buildingId/apartments/$apartmentId/users': typeof AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/reset_password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/cards'
    | '/admin/monitor'
    | '/admin/users'
    | '/admin/'
    | '/admin/buildings/$buildingId'
    | '/admin/buildings/$buildingId/apartments'
    | '/admin/buildings/$buildingId/events'
    | '/admin/buildings/$buildingId/live'
    | '/admin/buildings/$buildingId/readers'
    | '/admin/buildings/$buildingId/settings'
    | '/admin/buildings/$buildingId/users'
    | '/admin/buildings/$buildingId/'
    | '/admin/buildings/$buildingId/apartments/'
    | '/admin/buildings/$buildingId/apartments/$apartmentId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/reset_password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/cards'
    | '/admin/monitor'
    | '/admin/users'
    | '/admin'
    | '/admin/buildings/$buildingId/events'
    | '/admin/buildings/$buildingId/live'
    | '/admin/buildings/$buildingId/readers'
    | '/admin/buildings/$buildingId/settings'
    | '/admin/buildings/$buildingId/users'
    | '/admin/buildings/$buildingId'
    | '/admin/buildings/$buildingId/apartments'
    | '/admin/buildings/$buildingId/apartments/$apartmentId/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/reset_password'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/admin/cards'
    | '/admin/monitor'
    | '/admin/users'
    | '/admin/'
    | '/admin/buildings/$buildingId'
    | '/admin/buildings/$buildingId/apartments'
    | '/admin/buildings/$buildingId/events'
    | '/admin/buildings/$buildingId/live'
    | '/admin/buildings/$buildingId/readers'
    | '/admin/buildings/$buildingId/settings'
    | '/admin/buildings/$buildingId/users'
    | '/admin/buildings/$buildingId/'
    | '/admin/buildings/$buildingId/apartments/'
    | '/admin/buildings/$buildingId/apartments/$apartmentId/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  Reset_passwordRoute: typeof Reset_passwordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset_password': {
      id: '/reset_password'
      path: '/reset_password'
      fullPath: '/reset_password'
      preLoaderRoute: typeof Reset_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitor': {
      id: '/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AdminMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buildings/$buildingId': {
      id: '/admin/buildings/$buildingId'
      path: '/buildings/$buildingId'
      fullPath: '/admin/buildings/$buildingId'
      preLoaderRoute: typeof AdminBuildingsBuildingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buildings/$buildingId/': {
      id: '/admin/buildings/$buildingId/'
      path: '/'
      fullPath: '/admin/buildings/$buildingId/'
      preLoaderRoute: typeof AdminBuildingsBuildingIdIndexRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/apartments': {
      id: '/admin/buildings/$buildingId/apartments'
      path: '/apartments'
      fullPath: '/admin/buildings/$buildingId/apartments'
      preLoaderRoute: typeof AdminBuildingsBuildingIdApartmentsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/events': {
      id: '/admin/buildings/$buildingId/events'
      path: '/events'
      fullPath: '/admin/buildings/$buildingId/events'
      preLoaderRoute: typeof AdminBuildingsBuildingIdEventsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/live': {
      id: '/admin/buildings/$buildingId/live'
      path: '/live'
      fullPath: '/admin/buildings/$buildingId/live'
      preLoaderRoute: typeof AdminBuildingsBuildingIdLiveRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/readers': {
      id: '/admin/buildings/$buildingId/readers'
      path: '/readers'
      fullPath: '/admin/buildings/$buildingId/readers'
      preLoaderRoute: typeof AdminBuildingsBuildingIdReadersRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/settings': {
      id: '/admin/buildings/$buildingId/settings'
      path: '/settings'
      fullPath: '/admin/buildings/$buildingId/settings'
      preLoaderRoute: typeof AdminBuildingsBuildingIdSettingsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/users': {
      id: '/admin/buildings/$buildingId/users'
      path: '/users'
      fullPath: '/admin/buildings/$buildingId/users'
      preLoaderRoute: typeof AdminBuildingsBuildingIdUsersRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/apartments/': {
      id: '/admin/buildings/$buildingId/apartments/'
      path: '/'
      fullPath: '/admin/buildings/$buildingId/apartments/'
      preLoaderRoute: typeof AdminBuildingsBuildingIdApartmentsIndexRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdApartmentsRoute
    }
    '/admin/buildings/$buildingId/apartments/$apartmentId/users': {
      id: '/admin/buildings/$buildingId/apartments/$apartmentId/users'
      path: '/$apartmentId/users'
      fullPath: '/admin/buildings/$buildingId/apartments/$apartmentId/users'
      preLoaderRoute: typeof AdminBuildingsBuildingIdApartmentsApartmentIdUsersRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdApartmentsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminBuildingsBuildingIdApartmentsRouteChildren {
  AdminBuildingsBuildingIdApartmentsIndexRoute: typeof AdminBuildingsBuildingIdApartmentsIndexRoute
  AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute: typeof AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute
}

const AdminBuildingsBuildingIdApartmentsRouteChildren: AdminBuildingsBuildingIdApartmentsRouteChildren =
  {
    AdminBuildingsBuildingIdApartmentsIndexRoute:
      AdminBuildingsBuildingIdApartmentsIndexRoute,
    AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute:
      AdminBuildingsBuildingIdApartmentsApartmentIdUsersRoute,
  }

const AdminBuildingsBuildingIdApartmentsRouteWithChildren =
  AdminBuildingsBuildingIdApartmentsRoute._addFileChildren(
    AdminBuildingsBuildingIdApartmentsRouteChildren,
  )

interface AdminBuildingsBuildingIdRouteChildren {
  AdminBuildingsBuildingIdApartmentsRoute: typeof AdminBuildingsBuildingIdApartmentsRouteWithChildren
  AdminBuildingsBuildingIdEventsRoute: typeof AdminBuildingsBuildingIdEventsRoute
  AdminBuildingsBuildingIdLiveRoute: typeof AdminBuildingsBuildingIdLiveRoute
  AdminBuildingsBuildingIdReadersRoute: typeof AdminBuildingsBuildingIdReadersRoute
  AdminBuildingsBuildingIdSettingsRoute: typeof AdminBuildingsBuildingIdSettingsRoute
  AdminBuildingsBuildingIdUsersRoute: typeof AdminBuildingsBuildingIdUsersRoute
  AdminBuildingsBuildingIdIndexRoute: typeof AdminBuildingsBuildingIdIndexRoute
}

const AdminBuildingsBuildingIdRouteChildren: AdminBuildingsBuildingIdRouteChildren =
  {
    AdminBuildingsBuildingIdApartmentsRoute:
      AdminBuildingsBuildingIdApartmentsRouteWithChildren,
    AdminBuildingsBuildingIdEventsRoute: AdminBuildingsBuildingIdEventsRoute,
    AdminBuildingsBuildingIdLiveRoute: AdminBuildingsBuildingIdLiveRoute,
    AdminBuildingsBuildingIdReadersRoute: AdminBuildingsBuildingIdReadersRoute,
    AdminBuildingsBuildingIdSettingsRoute:
      AdminBuildingsBuildingIdSettingsRoute,
    AdminBuildingsBuildingIdUsersRoute: AdminBuildingsBuildingIdUsersRoute,
    AdminBuildingsBuildingIdIndexRoute: AdminBuildingsBuildingIdIndexRoute,
  }

const AdminBuildingsBuildingIdRouteWithChildren =
  AdminBuildingsBuildingIdRoute._addFileChildren(
    AdminBuildingsBuildingIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminCardsRoute: typeof AdminCardsRoute
  AdminMonitorRoute: typeof AdminMonitorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBuildingsBuildingIdRoute: typeof AdminBuildingsBuildingIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardsRoute: AdminCardsRoute,
  AdminMonitorRoute: AdminMonitorRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBuildingsBuildingIdRoute: AdminBuildingsBuildingIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  Reset_passwordRoute: Reset_passwordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
